
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-1
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjM2NDk0MTY3","is_bot":false,"login":"ErwanDev","name":"Erwan"},"headRefName":"Erwan-LocationQueryController","number":27,"title":"Added Location Controller and Test Coverage","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-1/pull/27"},{"author":{"id":"U_kgDOBXj-Bg","is_bot":false,"login":"chauAlex","name":""},"headRefName":"Alex-Tides-Controller","number":26,"title":"Added TideController and Test Coverage","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-1/pull/26"},{"author":{"id":"MDQ6VXNlcjQ0Njg5MjQw","is_bot":false,"login":"Johnsonchan105","name":"Johnson Chan"},"headRefName":"Johnson-Joke","number":25,"title":"Added Joke Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjY5Njk2Njcx","is_bot":false,"login":"Joseph-Foster","name":"Joseph Foster"},"headRefName":"Joseph-ZipCode","number":24,"title":"Added ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-1/pull/24"}]
